exports.WEAK_SIGNAL_THRESHOLD = 0.2;
exports.STRONG_SIGNAL_THRESHOLD = 0.7;
exports.SIGNALS = {
  STRONG_BUY: "STRONG_BUY",
  BUY: "BUY",
  HOLD: "HOLD",
  SELL: "SELL",
  STRONG_SELL: "STRONG_SELL",
};
exports.SIGNAL_WEIGHTS = {
  STRONG_BUY: 2.5,
  BUY: 2,
  HOLD: 1,
  SELL: 2,
  STRONG_SELL: 2.5,
};
